apiVersion: v1
kind: Pod
metadata:
  name: products-service-pod
  labels:
    app: products-service
spec:
  containers:
    - name: products-service
      image: products-service:v1
      ports:
        - containerPort: 8090