apiVersion: v1
kind: Pod
metadata:
  name: products-pod
  labels:
    app: products-app
spec:
  containers:
    - name: products-container
      image: products-image
      ports:
        - containerPort: 8090